version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            cache_from: ["172396373649.dkr.ecr.eu-central-1.amazonaws.com/signageos/file/runtime:latest"]
            target: dev
            tags: ["172396373649.dkr.ecr.eu-central-1.amazonaws.com/signageos/file/runtime:latest"]

        ports:
            - 8080
        volumes:
            - .:/app:delegated
        command: tail -f /dev/null
        working_dir: /app
        env_file:
            - ~/.signageos/npm.env
